version: '3.8'
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html:delegated

  artisan:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']

  composer:
    build:
      context: ./docker
      dockerfile: composer/Dockerfile
    volumes:
      - ./backend:/var/www/html

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./frontend:/var/www/html
  
  postgres:
    image: postgres:latest
    env_file:
      - ./.env